In [285]:
import numpy as np
from scipy import optimize
import chaospy as chaos

In [286]:
P = 5
normal = chaos.Normal()
psi = chaos.generate_expansion(P, normal)
psi

polynomial([1.0, q0, q0**2-1.0, q0**3-3.0*q0, q0**4-6.0*q0**2+3.0,
            q0**5-10.0*q0**3+15.0*q0])

In [287]:
M = np.zeros((P+1,P+1,P+1))
b = np.random.rand(P+1)
c = np.random.rand(P+1)
c

array([0.8111365 , 0.7672953 , 0.73081686, 0.17563572, 0.86442534,
       0.41598064])

In [288]:
for i in range(P+1):
    for j in range(P+1):
        for k in range(P+1):
            M[i, j, k] = chaos.E(psi[i]*psi[j]*psi[k], normal).round(5)

In [289]:
d = np.zeros(P+1)
for k in range(P+1):
    for i in range(P+1):
        for j in range(P+1):
            d[k] += (b[i]*b[j] + c[i]*c[j])*M[i, j, k]
d

array([  103.17535743,   259.95067017,  1087.84754253,  3079.54912399,
       11854.33054197, 29219.03884349])

In [290]:
def residual(a):
    res = np.zeros(P+1)
    for k in range(P+1):
        for i in range(P+1):
            for j in range(P+1):
                res[k] += a[i]*a[j]*M[i, j, k]
        res[k] -= d[k]
    return res

In [291]:
a0 = np.sqrt(b**2 + c**2)
a0

array([0.88627644, 0.77002411, 0.76987555, 0.79989879, 1.26710783,
       0.69665268])

In [292]:
sol = optimize.root(residual, a0)

In [293]:
sol.success

True

In [294]:
a = sol.x
a

array([ 1.89353243, -0.08793878,  0.7746328 ,  0.81596606,  1.224443  ,
        0.69764478])